// Generated by CoffeeScript 1.10.0
(function() {
  var User;

  User = (function() {
    function User() {
      this.view = null;
      this.uid = 0;
      this.username = '';
      this.update();
    }

    User.prototype.update = function() {
      if (this.view != null) {
        return this.view.update();
      }
    };

    User.prototype.login = function(username, password, handler) {
      return $.ajax({
        url: '/backend/login/',
        type: 'POST',
        data: JSON.stringify({
          username: username,
          password: password
        }),
        contentType: "application/json",
        dataType: 'json'
      }).done((function(_this) {
        return function(result) {
          if (result.result === 'succeeded') {
            _this.uid = result.uid;
            _this.username = username;
          } else {
            alert(result.errorMessage);
          }
          return _this.update();
        };
      })(this));
    };

    User.prototype.logout = function(handler) {
      return $.ajax({
        url: '/backend/logout/',
        type: 'POST',
        data: JSON.stringify({
          uid: this.uid
        }),
        contentType: "application/json",
        dataType: 'json'
      }).done((function(_this) {
        return function(result) {
          if (result.result === 'succeeded') {
            _this.uid = 0;
            _this.username = '';
          } else {
            alert(result.errorMessage);
          }
          _this.update();
          return $("#navbar_password").val('');
        };
      })(this));
    };

    User.prototype.registration = function(username, password, password2, email, handler) {
      return $.ajax({
        url: '/backend/registration/',
        type: 'POST',
        data: JSON.stringify({
          username: username,
          password: password,
          repeatedPassword: password2,
          email: email
        }),
        contentType: "application/json",
        dataType: 'json'
      }).done((function(_this) {
        return function(result) {
          if (result.result !== 'succeeded') {
            alert(result.errorMessage);
          }
          return _this.update();
        };
      })(this));
    };

    User.prototype.updateinfo = function(old_password, new_password, new_password2, new_email, handler) {
      return $.ajax({
        url: '/backend/updateinfo/',
        type: 'POST',
        data: JSON.stringify({
          uid: this.uid,
          oldPassword: old_password,
          newPassword: new_password,
          repeatedPassword: new_password2,
          new_email: new_email
        }),
        contentType: "application/json",
        dataType: 'json'
      }).done((function(_this) {
        return function(result) {
          if (result.result !== 'succeeded') {
            alert(result.errorMessage);
          }
          return _this.update();
        };
      })(this));
    };

    User.prototype.register = function(loginUI) {
      this.view = loginUI;
      return this.view._register(this);
    };

    User.prototype.loginCheck = function() {
      return $.ajax({
        url: '/backend/login/',
        type: 'GET',
        dataType: 'json'
      }).done((function(_this) {
        return function(result) {
          if (result.result === 'succeeded') {
            _this.username = result.username;
          } else {
            _this.username = '';
          }
          return _this.update();
        };
      })(this));
    };

    return User;

  })();

  module.exports = User;

}).call(this);

//# sourceMappingURL=user.js.map
